---
name: "Release"

on:
  push:
    branches:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Setup SP
        uses: rumblefrog/setup-sp@v1.0.1

      - name: Compile plugins
        run: |
          for file in scripting/${plugin_name}*.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -w234 -O2 -v2 -i ./scripting/include $file -o payload-webhook.smx
          done
        working-directory: ${{ github.workspace }}

      - name: Upload compiled plugin
        uses: actions/upload-artifact@v2
        with:
          name: payload-webhook
          path: payload-webhook.smx
          if-no-files-found: error

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ github.ref }}
          prerelease: false
          files: |
            *.smx
            scripting/include/logstf.inc
            scripting/include/SteamWorks.inc